plugins {
    id 'com.android.application'
}

android {
    namespace 'com.payzo.minerush'
    compileSdk 34

    defaultConfig {
        applicationId "com.payzo.minerush"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.0.1"
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword 'minerush@2026'
            keyAlias 'minerushkey'
            keyPassword 'minerush@2026'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // 1. Google AdMob Official SDK
    implementation 'com.google.android.gms:play-services-ads:23.0.0'

    // 2. AppLovin MAX SDK
    implementation 'com.applovin:applovin-sdk:13.0.1'
}
